### ISSUE TITLE
res should be out of findAndUpdate  

### ISSUE THREAD

**Issue by phreakphreak** [helloitsrufio/Southern-Paiute-Talking-Dictionary#1]
the res() must not be inside the findAndUpdate function and at the same time do a destructuring to update the changes with req.body

![image](https://user-images.githubusercontent.com/91038818/152882063-11ffd43c-4c98-4983-a743-0b4e41605ace.png)

**Comment by phreakphreak** [comment]
newfileName is not defined in the context, maybe because of that it is undefined, tools like eslint help you to control these bugs.

**Comment by helloitsrufio** [comment]
Res removed.
