### ISSUE TITLE
Add Footer Partial

### ISSUE THREAD

**Issue by devlark** [helloitsrufio/Southern-Paiute-Talking-Dictionary#7]
# Description

Add a footer partial to avoid the pain of changing the footer content everywhere.

[Southern-Paiute-Talking-Dictionary](https://github.com/helloitsrufio/Southern-Paiute-Talking-Dictionary)/[views](https://github.com/helloitsrufio/Southern-Paiute-Talking-Dictionary/tree/master/views)/partials/

**Comment by helloitsrufio** [comment]
:shipit:
